SELECT 	H.CODPRODUTO,
		P.EAN,
		P.DESCRICAO,
		SUM(H.AJUSTE) AS QUANTIDADE_ATUAL,
		(SELECT MAX(H2.DATA) FROM HMOVIMENTACAO H2 WHERE H.CODPRODUTO = H2.CODPRODUTO AND H2.DESCRMOV = 'ENTRADA ACERTO ENTRADA')
FROM HMOVIMENTACAO H 
     INNER JOIN PRODUTO P ON (P.COD_PRODUTO = H.CODPRODUTO)
WHERE H.DATA >= '2020-10-01'
	AND H.DATA <= '2020-12-07'
	--AND (H.DESCRMOV = 'ENTRADA ACERTO ENTRADA'
	--OR H.DESCRMOV LIKE '%CUPOM%')
GROUP BY 1,2,3,5
HAVING SUM(H.AJUSTE) > 0;
